-- Tileset mapping generated by tile.py at 2026-07-04 22:58:14
-- Marked: 26 tiles
-- Bitmask values: 0 = Off, 1 = On, 2 = Ignore (Minimal 3x3 Autotile)

return {
    source = 'src/assets/pixel-set-library/dungen-tile/Tile Set.png',
    cols = 16,
    rows = 16,
    tile_width = 16,
    tile_height = 16,
    padding = 0,
    count = 26,
    tiles = {
        [0] = { col = 6, row = 1 },
        [1] = { col = 7, row = 1 },
        [2] = { col = 8, row = 1 },
        [3] = { col = 9, row = 1 },
        [4] = { col = 10, row = 1 },
        [5] = { col = 6, row = 2 },
        [6] = { col = 7, row = 2 },
        [7] = { col = 8, row = 2 },
        [8] = { col = 9, row = 2 },
        [9] = { col = 10, row = 2 },
        [10] = { col = 1, row = 3, bitmask = {
            {0, 0, 0},
            {0, 1, 1},
            {0, 1, 0},
        } },
        [11] = { col = 2, row = 3, bitmask = {
            {0, 0, 0},
            {1, 1, 1},
            {0, 1, 0},
        } },
        [12] = { col = 3, row = 3, bitmask = {
            {0, 0, 0},
            {1, 1, 0},
            {0, 1, 0},
        } },
        [13] = { col = 4, row = 3, bitmask = {
            {0, 0, 0},
            {0, 1, 0},
            {0, 1, 0},
        } },
        [14] = { col = 1, row = 4, bitmask = {
            {0, 1, 0},
            {0, 1, 1},
            {0, 1, 0},
        } },
        [15] = { col = 2, row = 4, bitmask = {
            {0, 1, 0},
            {1, 1, 1},
            {0, 1, 0},
        } },
        [16] = { col = 3, row = 4, bitmask = {
            {0, 1, 0},
            {1, 1, 0},
            {0, 1, 0},
        } },
        [17] = { col = 4, row = 4, bitmask = {
            {0, 1, 0},
            {0, 1, 0},
            {0, 1, 0},
        } },
        [18] = { col = 1, row = 5, bitmask = {
            {0, 1, 0},
            {0, 1, 1},
            {0, 0, 0},
        } },
        [19] = { col = 2, row = 5, bitmask = {
            {0, 1, 0},
            {1, 1, 1},
            {0, 0, 0},
        } },
        [20] = { col = 3, row = 5, bitmask = {
            {0, 1, 0},
            {1, 1, 0},
            {0, 0, 0},
        } },
        [21] = { col = 4, row = 5, bitmask = {
            {0, 1, 0},
            {0, 1, 0},
            {0, 0, 0},
        } },
        [22] = { col = 1, row = 6, bitmask = {
            {0, 0, 0},
            {0, 1, 1},
            {0, 0, 0},
        } },
        [23] = { col = 2, row = 6, bitmask = {
            {0, 0, 0},
            {1, 1, 1},
            {0, 0, 0},
        } },
        [24] = { col = 3, row = 6, bitmask = {
            {0, 0, 0},
            {1, 1, 0},
            {0, 0, 0},
        } },
        [25] = { col = 4, row = 6, bitmask = {
            {0, 0, 0},
            {0, 1, 0},
            {0, 0, 0},
        } },
    },
    groups = {
        ["wall"] = { tiles = { 7, 3, 8, 5, 4, 2, 1, 6, 0, 9 } },
        ["ground"] = { tiles = { 15, 10, 11, 22, 21, 14, 13, 12, 20, 19, 18, 17, 16, 25, 24, 23 } },
    },
}
