-- Tileset mapping generated by tile.py at 2026-07-04 22:13:47
-- Marked: 10 tiles
-- Bitmask values: 0 = Off, 1 = On, 2 = Ignore (Minimal 3x3 Autotile)

return {
    source = 'src/assets/pixel-set-library/dungen-tile/Tile Set.png',
    cols = 16,
    rows = 16,
    tile_width = 16,
    tile_height = 16,
    padding = 0,
    count = 10,
    tiles = {
        [0] = { col = 6, row = 1 },
        [1] = { col = 7, row = 1 },
        [2] = { col = 8, row = 1 },
        [3] = { col = 9, row = 1 },
        [4] = { col = 10, row = 1 },
        [5] = { col = 6, row = 2 },
        [6] = { col = 7, row = 2 },
        [7] = { col = 8, row = 2 },
        [8] = { col = 9, row = 2 },
        [9] = { col = 10, row = 2 },
    },
    groups = {
        ["wall"] = { tiles = { 3, 8, 5, 4, 2, 1, 7, 6, 0, 9 } },
    },
}
