-- Tileset mapping generated by tile.py at 2026-06-25 21:25:12
-- Marked: 2 tiles
-- Bitmask values: 0 = Off, 1 = On, 2 = Ignore (Minimal 3x3 Autotile)

return {
    source = 'src/assets/pixel-set-library/dungen-tile/Tile Set.png',
    cols = 16,
    rows = 16,
    tile_width = 16,
    tile_height = 16,
    padding = 0,
    count = 2,
    tiles = {
        [0] = { col = 3, row = 2, properties = { solid = true } },
        [1] = { col = 4, row = 2 },
    },
}
