-- Auto-generated by TileSet Exporter
return {
    ["format_version"] = 1,
    ["tile_width"] = 16,
    ["tile_height"] = 16,
    ["custom_data_layers"] = {
        {
            ["name"] = "Ground",
            ["type"] = "bool",
        },
    },
    ["terrain_sets"] = {
        {
            ["mode"] = "tiles",
            ["terrains"] = {
                {
                    ["name"] = "Terrain 0",
                    ["color"] = "#ffdb00",
                },
            },
        },
    },
    ["columns"] = 16,
    ["rows"] = 16,
    ["texture_path"] = "Tile Set.png",
    ["texture_res_path"] = "res://assets/Tile Set.png",
    ["tiles"] = {
        {
            ["col"] = 1,
            ["row"] = 3,
            ["terrain_set"] = 0,
            ["terrain"] = 0,
            ["peering_bits"] = {
                ["right_side"] = 0,
                ["bottom_side"] = 0,
            },
            ["bitmask"] = 3,
            ["custom_data"] = {
                ["Ground"] = true,
            },
        },
        {
            ["col"] = 1,
            ["row"] = 4,
            ["terrain_set"] = 0,
            ["terrain"] = 0,
            ["peering_bits"] = {
                ["right_side"] = 0,
                ["bottom_side"] = 0,
                ["top_side"] = 0,
            },
            ["bitmask"] = 11,
            ["custom_data"] = {
                ["Ground"] = true,
            },
        },
        {
            ["col"] = 1,
            ["row"] = 5,
            ["terrain_set"] = 0,
            ["terrain"] = 0,
            ["peering_bits"] = {
                ["right_side"] = 0,
                ["top_side"] = 0,
            },
            ["bitmask"] = 9,
            ["custom_data"] = {
                ["Ground"] = true,
            },
        },
        {
            ["col"] = 1,
            ["row"] = 6,
            ["terrain_set"] = 0,
            ["terrain"] = 0,
            ["peering_bits"] = {
                ["right_side"] = 0,
            },
            ["bitmask"] = 1,
            ["custom_data"] = {
                ["Ground"] = true,
            },
        },
        {
            ["col"] = 2,
            ["row"] = 3,
            ["terrain_set"] = 0,
            ["terrain"] = 0,
            ["peering_bits"] = {
                ["right_side"] = 0,
                ["bottom_side"] = 0,
                ["left_side"] = 0,
            },
            ["bitmask"] = 7,
            ["custom_data"] = {
                ["Ground"] = true,
            },
        },
        {
            ["col"] = 2,
            ["row"] = 4,
            ["terrain_set"] = 0,
            ["terrain"] = 0,
            ["peering_bits"] = {
                ["right_side"] = 0,
                ["bottom_side"] = 0,
                ["left_side"] = 0,
                ["top_side"] = 0,
            },
            ["bitmask"] = 15,
            ["custom_data"] = {
                ["Ground"] = true,
            },
        },
        {
            ["col"] = 2,
            ["row"] = 5,
            ["terrain_set"] = 0,
            ["terrain"] = 0,
            ["peering_bits"] = {
                ["right_side"] = 0,
                ["left_side"] = 0,
                ["top_side"] = 0,
            },
            ["bitmask"] = 13,
            ["custom_data"] = {
                ["Ground"] = true,
            },
        },
        {
            ["col"] = 2,
            ["row"] = 6,
            ["terrain_set"] = 0,
            ["terrain"] = 0,
            ["peering_bits"] = {
                ["right_side"] = 0,
                ["left_side"] = 0,
            },
            ["bitmask"] = 5,
            ["custom_data"] = {
                ["Ground"] = true,
            },
        },
        {
            ["col"] = 3,
            ["row"] = 3,
            ["terrain_set"] = 0,
            ["terrain"] = 0,
            ["peering_bits"] = {
                ["bottom_side"] = 0,
                ["left_side"] = 0,
            },
            ["bitmask"] = 6,
            ["custom_data"] = {
                ["Ground"] = true,
            },
        },
        {
            ["col"] = 3,
            ["row"] = 4,
            ["terrain_set"] = 0,
            ["terrain"] = 0,
            ["peering_bits"] = {
                ["bottom_side"] = 0,
                ["left_side"] = 0,
                ["top_side"] = 0,
            },
            ["bitmask"] = 14,
            ["custom_data"] = {
                ["Ground"] = true,
            },
        },
        {
            ["col"] = 3,
            ["row"] = 5,
            ["terrain_set"] = 0,
            ["terrain"] = 0,
            ["peering_bits"] = {
                ["left_side"] = 0,
                ["top_side"] = 0,
            },
            ["bitmask"] = 12,
            ["custom_data"] = {
                ["Ground"] = true,
            },
        },
        {
            ["col"] = 3,
            ["row"] = 6,
            ["terrain_set"] = 0,
            ["terrain"] = 0,
            ["peering_bits"] = {
                ["left_side"] = 0,
            },
            ["bitmask"] = 4,
            ["custom_data"] = {
                ["Ground"] = true,
            },
        },
        {
            ["col"] = 4,
            ["row"] = 3,
            ["terrain_set"] = 0,
            ["terrain"] = 0,
            ["peering_bits"] = {
                ["bottom_side"] = 0,
            },
            ["bitmask"] = 2,
            ["custom_data"] = {
                ["Ground"] = true,
            },
        },
        {
            ["col"] = 4,
            ["row"] = 4,
            ["terrain_set"] = 0,
            ["terrain"] = 0,
            ["peering_bits"] = {
                ["bottom_side"] = 0,
                ["top_side"] = 0,
            },
            ["bitmask"] = 10,
            ["custom_data"] = {
                ["Ground"] = true,
            },
        },
        {
            ["col"] = 4,
            ["row"] = 5,
            ["terrain_set"] = 0,
            ["terrain"] = 0,
            ["peering_bits"] = {
                ["top_side"] = 0,
            },
            ["bitmask"] = 8,
            ["custom_data"] = {
                ["Ground"] = true,
            },
        },
        {
            ["col"] = 4,
            ["row"] = 6,
            ["terrain_set"] = 0,
            ["terrain"] = 0,
            ["peering_bits"] = {},
            ["bitmask"] = 0,
            ["custom_data"] = {
                ["Ground"] = true,
            },
        },
    },
    ["bitmask_map"] = {
        [0] = {
            [0] = {
                [3] = { 1, 3 },
                [11] = { 1, 4 },
                [9] = { 1, 5 },
                [1] = { 1, 6 },
                [7] = { 2, 3 },
                [15] = { 2, 4 },
                [13] = { 2, 5 },
                [5] = { 2, 6 },
                [6] = { 3, 3 },
                [14] = { 3, 4 },
                [12] = { 3, 5 },
                [4] = { 3, 6 },
                [2] = { 4, 3 },
                [10] = { 4, 4 },
                [8] = { 4, 5 },
                [0] = { 4, 6 },
            },
        },
    },
}
